<a href="https://colab.research.google.com/github/dechl-98/etl-data-pipeline/blob/main/notebook/clientes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install sqlalchemy psycopg2-binary

Requirement already satisfied: sqlalchemy in /usr/local/lib/python3.12/dist-packages (2.0.48)
Collecting psycopg2-binary
  Downloading psycopg2_binary-2.9.11-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (4.9 kB)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy) (3.3.2)
Requirement already satisfied: typing-extensions>=4.6.0 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy) (4.15.0)
Downloading psycopg2_binary-2.9.11-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (4.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.2/4.2 MB 32.5 MB/s eta 0:00:00
Installing collected packages: psycopg2-binary
Successfully installed psycopg2-binary-2.9.11

In [ ]:
from sqlalchemy import create_engine
import pandas as pd
database_url = "postgresql://etl_seguros_67zv_user:TV9HLZks2Q2TRRYt42vPETVOyKIcAYx2@dpg-d6qu70shg0os73b4gfj0-a.oregon-postgres.render.com/etl_seguros_67zv"

In [ ]:
engine = create_engine(database_url)

test = pd.read_sql("SELECT 1", engine)

print(test)

   ?column?
0         1

In [ ]:
import pandas as pd

In [ ]:
https://raw.githubusercontent.com/dechl-98/etl-data-pipeline/main/data/clientes.csv

SyntaxError: invalid syntax (2395819275.py, line 1)

In [ ]:
url = "https://raw.githubusercontent.com/dechl-98/etl-data-pipeline/main/data/clientes.csv"

df = pd.read_csv(url)

df.head()

HTTPError: HTTP Error 404: Not Found

In [ ]:
url = "https://raw.githubusercontent.com/dechl-98/etl-data-pipeline/main/data/clientes.csv"

df = pd.read_csv(url)

df.head()

EmptyDataError: No columns to parse from file

In [ ]:
https://github.com/dechl-98/etl-data-pipeline/blob/main/data/clientes.csv

SyntaxError: invalid syntax (876605040.py, line 1)

In [13]:
url = "https://raw.githubusercontent.com/dechl-98/etl-data-pipeline/main/data/clientes.csv"

df = pd.read_csv(url)

df.head()

EmptyDataError: No columns to parse from file

In [14]:
import pandas as pd

In [15]:
url = "https://raw.githubusercontent.com/dechl-98/etl-data-pipeline/refs/heads/main/data/Raw/clientes.csv"

In [16]:
df = pd.read_csv(url)

df.head()

,id_cliente,nombre,email,genero,fecha_nacimiento,ciudad,segmento
0,1,José Chávez Pérez,jose.chavez.perez1@gmail.com,Hombre,2011/11/24,SanMiguel,NaN
1,2,Daniela Rojas Ortiz,daniela.rojas.ortiz2@seguro.sv,NaN,01-02-80,Sta. Ana,NaN
2,3,Ricardo Cruz Flores,ricardo.cruz.flores3@example.com,Masculino,06-18-79,S. Miguel,NaN
3,4,María Pérez Pérez,maria.perez.perez4@correo.com,Masculino,1960-09-29,LaLibertad,REGULAR
4,5,Fernanda Chávez Rojas,fernanda.chavez.rojas5@seguro.sv,NaN,1945/08/02,San Salvador,Pyme

In [17]:
df.shape
df.columns
df.info()
df.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3030 entries, 0 to 3029
Data columns (total 7 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   id_cliente        3030 non-null   int64
 1   nombre            3030 non-null   object
 2   email             3030 non-null   object
 3   genero            2435 non-null   object
 4   fecha_nacimiento  3030 non-null   object
 5   ciudad            3030 non-null   object
 6   segmento          2433 non-null   object
dtypes: int64(1), object(6)
memory usage: 165.8+ KB

id_cliente            0
nombre                0
email                 0
genero              595
fecha_nacimiento      0
ciudad                0
segmento            597
dtype: int64

In [18]:
clientes = df.copy()

clientes.columns = clientes.columns.str.strip().str.lower()

for col in clientes.select_dtypes(include='object').columns:
    clientes[col] = clientes[col].astype(str).str.strip()

clientes = clientes.replace(r'^\s*$', pd.NA, regex=True)

clientes['email'] = clientes['email'].str.lower()

clientes['fecha_nacimiento'] = pd.to_datetime(clientes['fecha_nacimiento'], errors='coerce')

clientes = clientes.drop_duplicates()

In [19]:
validos = clientes[
    clientes['nombre'].notna() &
    clientes['email'].notna()
].copy()

rechazados = clientes[
    clientes['nombre'].isna() |
    clientes['email'].isna()
].copy()

In [21]:
def motivo(row):

    motivos = []

    if pd.isna(row['nombre']):
        motivos.append("nombre_vacio")

    if pd.isna(row['email']):
        motivos.append("email_vacio")

    return ",".join(motivos)

rechazados["motivo_rechazo"] = rechazados.apply(motivo, axis=1)

In [22]:
validos.to_csv("clientes_curated.csv", index=False)

rechazados.to_csv("clientes_rejects.csv", index=False)

In [23]:
!pip install sqlalchemy psycopg2-binary

from sqlalchemy import create_engine
import pandas as pd

database_url = "postgresql://etl_user:H1p5ZGWEjVtVLYwGVZgLHieAbGWE48cy@dpg-d6qt0ecr85hc73f3paqg-a.oregon-postgres.render.com/etl_seguros"

engine = create_engine(database_url)

test = pd.read_sql("SELECT 1", engine)

print(test)

Requirement already satisfied: sqlalchemy in /usr/local/lib/python3.12/dist-packages (2.0.48)
Requirement already satisfied: psycopg2-binary in /usr/local/lib/python3.12/dist-packages (2.9.11)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy) (3.3.2)
Requirement already satisfied: typing-extensions>=4.6.0 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy) (4.15.0)
   ?column?
0         1

In [24]:
validos.to_sql(
    'clientes_curated',
    engine,
    if_exists='append',
    index=False
)

rechazados.to_sql(
    'clientes_rejects',
    engine,
    if_exists='append',
    index=False
)

0

In [26]:
pd.read_sql(
"SELECT to_char(fecha_nacimiento, 'YYYY-MM-DD') FROM clientes_curated LIMIT 10",
engine
)

      to_char
0  2011-11-24
1        None
2        None
3        None
4  1945-08-02
5  1966-10-15
6        None
7        None
8        None
9        None

In [28]:
pd.read_sql(
"SELECT REPLACE(SUBSTR(fecha_nacimiento::text, 1, 10 ),  '-','/') AS fecha_estandarizada FROM clientes_curated LIMIT 10",engine)

ProgrammingError: (psycopg2.errors.UndefinedFunction) function substr(timestamp without time zone, integer, integer) does not exist
LINE 1: SELECT REPLACE(SUBSTR(fecha_nacimiento, 1, 10 ),  '-','/') A...
                       ^
HINT:  No function matches the given name and argument types. You might need to add explicit type casts.

[SQL: SELECT REPLACE(SUBSTR(fecha_nacimiento, 1, 10 ),  '-','/') AS fecha_estandarizada FROM clientes_curated LIMIT 10]
(Background on this error at: https://sqlalche.me/e/20/f405)

In [29]:
pd.read_sql("SELECT REPLACE(SUBSTR(fecha_nacimiento, 1, 10 ),  '-','/') AS fecha_estandarizada FROM clientes_curated LIMIT 10",engine)

ProgrammingError: (psycopg2.errors.UndefinedFunction) function substr(timestamp without time zone, integer, integer) does not exist
LINE 1: SELECT REPLACE(SUBSTR(fecha_nacimiento, 1, 10 ),  '-','/') A...
                       ^
HINT:  No function matches the given name and argument types. You might need to add explicit type casts.

[SQL: SELECT REPLACE(SUBSTR(fecha_nacimiento, 1, 10 ),  '-','/') AS fecha_estandarizada FROM clientes_curated LIMIT 10]
(Background on this error at: https://sqlalche.me/e/20/f405)

In [30]:
pd.read_sql("SELECT TO_CHAR(fecha_nacimiento, 'YYYY/MM/DD') AS fecha_estandarizada FROM clientes_curated LIMIT 10", engine)

  fecha_estandarizada
0          2011/11/24
1                None
2                None
3                None
4          1945/08/02
5          1966/10/15
6                None
7                None
8                None
9                None

In [31]:
pd.read_sql("SELECT REPLACE(SUBSTR(fecha_nacimiento::TEXT, 1, 10), '-', '/') AS fecha_estandarizada FROM clientes_curated LIMIT 10", engine)

  fecha_estandarizada
0          2011/11/24
1                None
2                None
3                None
4          1945/08/02
5          1966/10/15
6                None
7                None
8                None
9                None