<a href="https://colab.research.google.com/github/dechl-98/etl-data-pipeline/blob/main/notebook/corredores.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

url = "https://raw.githubusercontent.com/dechl-98/etl-data-pipeline/refs/heads/main/data/Raw/corredores.csv"

df = pd.read_csv(url)

df.head()

   id_corredor               nombre         zona    nivel  anios_experiencia
0            1    José López Flores  Paracentral      Mid                4.0
1            2    José Ortiz García     Centro     Junior                0.0
2            3   María Ramírez Cruz       Centro  SENIOR                 6.0
3            4  Fernanda Rojas Cruz          NaN  SENIOR                 8.0
4            5      Ana Gómez Rojas          NaN   Senior                4.0

In [2]:
df.shape
df.columns
df.info()
df.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 80 entries, 0 to 79
Data columns (total 5 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   id_corredor        80 non-null     int64
 1   nombre             80 non-null     object
 2   zona               63 non-null     object
 3   nivel              68 non-null     object
 4   anios_experiencia  76 non-null     float64
dtypes: float64(1), int64(1), object(3)
memory usage: 3.3+ KB

id_corredor           0
nombre                0
zona                 17
nivel                12
anios_experiencia     4
dtype: int64

In [3]:
corredores_clean = df.copy()

corredores_clean.columns = corredores_clean.columns.str.strip().str.lower()

for col in corredores_clean.select_dtypes(include='object').columns:
    corredores_clean[col] = corredores_clean[col].astype(str).str.strip()

corredores_clean = corredores_clean.replace(r'^\s*$', pd.NA, regex=True)

corredores_clean = corredores_clean.drop_duplicates()

display(corredores_clean.head())

   id_corredor               nombre         zona   nivel  anios_experiencia
0            1    José López Flores  Paracentral     Mid                4.0
1            2    José Ortiz García       Centro  Junior                0.0
2            3   María Ramírez Cruz       Centro  SENIOR                6.0
3            4  Fernanda Rojas Cruz          nan  SENIOR                8.0
4            5      Ana Gómez Rojas          nan  Senior                4.0

In [4]:
validos_corredores = corredores_clean[
    corredores_clean['nombre'].notna() &
    corredores_clean['zona'].notna()
].copy()

rechazados_corredores = corredores_clean[
    corredores_clean['nombre'].isna() |
    corredores_clean['zona'].isna()
].copy()

print("Valid Corredores (first 5 rows):")
display(validos_corredores.head())

print("\nRejected Corredores (first 5 rows):")
display(rechazados_corredores.head())

Valid Corredores (first 5 rows):

   id_corredor               nombre         zona   nivel  anios_experiencia
0            1    José López Flores  Paracentral     Mid                4.0
1            2    José Ortiz García       Centro  Junior                0.0
2            3   María Ramírez Cruz       Centro  SENIOR                6.0
3            4  Fernanda Rojas Cruz          nan  SENIOR                8.0
4            5      Ana Gómez Rojas          nan  Senior                4.0

Rejected Corredores (first 5 rows):

Empty DataFrame
Columns: [id_corredor, nombre, zona, nivel, anios_experiencia]
Index: []

In [5]:
def motivo(row):
    motivos = []

    if pd.isna(row['nombre']):
        motivos.append("nombre_vacio")

    if pd.isna(row['zona']):
        motivos.append("zona_vacia")

    return ",".join(motivos)

rechazados_corredores["motivo_rechazo"] = rechazados_corredores.apply(motivo, axis=1)

display(rechazados_corredores.head())

Empty DataFrame
Columns: [id_corredor, nombre, zona, nivel, anios_experiencia, motivo_rechazo]
Index: []

In [6]:
validos_corredores.to_csv("corredores_curated.csv", index=False)
rechazados_corredores.to_csv("corredores_rejects.csv", index=False)

In [7]:
!pip install sqlalchemy psycopg2-binary

from sqlalchemy import create_engine
import pandas as pd

database_url = "postgresql://etl_seguros_67zv_user:TV9HLZks2Q2TRRYt42vPETVOyKIcAYx2@dpg-d6qu70shg0os73b4gfj0-a.oregon-postgres.render.com/etl_seguros_67zv"
engine = create_engine(database_url)

test = pd.read_sql("SELECT 1", engine)

print(test)

Requirement already satisfied: sqlalchemy in /usr/local/lib/python3.12/dist-packages (2.0.48)
Collecting psycopg2-binary
  Downloading psycopg2_binary-2.9.11-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (4.9 kB)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy) (3.3.2)
Requirement already satisfied: typing-extensions>=4.6.0 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy) (4.15.0)
Downloading psycopg2_binary-2.9.11-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (4.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.2/4.2 MB 38.4 MB/s eta 0:00:00
Installing collected packages: psycopg2-binary
Successfully installed psycopg2-binary-2.9.11
   ?column?
0         1

In [8]:
validos_corredores.to_sql(
    'corredores_curated',
    engine,
    if_exists='append',
    index=False
)

rechazados_corredores.to_sql(
    'corredores_rejects',
    engine,
    if_exists='append',
    index=False
)

print("DataFrames uploaded to PostgreSQL successfully.")

DataFrames uploaded to PostgreSQL successfully.

In [9]:
corredores_curated_db = pd.read_sql(
    "SELECT * FROM corredores_curated LIMIT 10",
    engine
)
display(corredores_curated_db)

   id_corredor                 nombre         zona   nivel  anios_experiencia
0            1      José López Flores  Paracentral     Mid                4.0
1            2      José Ortiz García       Centro  Junior                0.0
2            3     María Ramírez Cruz       Centro  SENIOR                6.0
3            4    Fernanda Rojas Cruz          nan  SENIOR                8.0
4            5        Ana Gómez Rojas          nan  Senior                4.0
5            6  Sofía Reyes Hernández    Occidente   Elite                3.0
6            7   Pedro Vásquez Torres        Costa     nan                1.0
7            8  Paula Ortiz Hernández       Centro  Junior               17.0
8            9  Carlos Torres Vásquez  Paracentral  junior                2.0
9           10     Juan Cruz Castillo    Occidente     nan                7.0