<a href="https://colab.research.google.com/github/dechl-98/etl-data-pipeline/blob/main/notebook/polizas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

url = "https://raw.githubusercontent.com/dechl-98/etl-data-pipeline/refs/heads/main/data/Raw/polizas.csv"

df = pd.read_csv(url)

df.head()

,id_poliza,fecha_emision,id_cliente,id_corredor,id_aseguradora,id_tipo_seguro,prima,comision,monto_asegurado
0,1,NaN,184,42,15,2,"829,53",NaN,139253.11
1,2,2026/02/16,2408,35,11,12,NaN,"12,22","27.544,32"
2,3,02-14-25,540,42,4,9,1611.53,"92,05","173,298.36"
3,4,09-01-2026,2821,40,10,5,1866.62,456.99,244461.27
4,5,2026-02-13,945,23,9,11,-,"324,08",123407.75

In [2]:
df.shape
df.columns
df.info()
df.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25150 entries, 0 to 25149
Data columns (total 9 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   id_poliza        25150 non-null  int64
 1   fecha_emision    22739 non-null  object
 2   id_cliente       25150 non-null  int64
 3   id_corredor      25150 non-null  int64
 4   id_aseguradora   25150 non-null  int64
 5   id_tipo_seguro   25150 non-null  int64
 6   prima            21840 non-null  object
 7   comision         21715 non-null  object
 8   monto_asegurado  21787 non-null  object
dtypes: int64(5), object(4)
memory usage: 1.7+ MB

id_poliza             0
fecha_emision      2411
id_cliente            0
id_corredor           0
id_aseguradora        0
id_tipo_seguro        0
prima              3310
comision           3435
monto_asegurado    3363
dtype: int64

In [5]:
import numpy as np

polizas_df = df.copy()

# Standardize column names
polizas_df.columns = polizas_df.columns.str.strip().str.lower()

# Strip whitespace from object columns and replace empty strings with NA
for col in polizas_df.select_dtypes(include='object').columns:
    polizas_df[col] = polizas_df[col].astype(str).str.strip()
    polizas_df[col] = polizas_df[col].replace(r'^\s*$', pd.NA, regex=True)

# Convert 'fecha_emision' to datetime
polizas_df['fecha_emision'] = pd.to_datetime(polizas_df['fecha_emision'], errors='coerce')

# Clean and convert 'prima', 'comision', and 'monto_asegurado' to numeric
for col in ['prima', 'comision', 'monto_asegurado']:
    # Replace comma with dot for decimal separation
    # Replace '-' with NaN, as it's a non-numeric placeholder
    if col in polizas_df.columns:
        polizas_df[col] = polizas_df[col].astype(str).str.replace('.', '', regex=False)
        polizas_df[col] = polizas_df[col].str.replace(',', '.', regex=False)
        polizas_df[col] = polizas_df[col].replace('-', np.nan)
        polizas_df[col] = pd.to_numeric(polizas_df[col], errors='coerce')

# Drop duplicate rows
polizas_df = polizas_df.drop_duplicates()
print('Cleaned DataFrame info:')
polizas_df.info()
print('\nNumber of null values after cleaning:')
print(polizas_df.isnull().sum())
display(polizas_df.head())

Cleaned DataFrame info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25150 entries, 0 to 25149
Data columns (total 9 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   id_poliza        25150 non-null  int64
 1   fecha_emision    4522 non-null   datetime64[ns]
 2   id_cliente       25150 non-null  int64
 3   id_corredor      25150 non-null  int64
 4   id_aseguradora   25150 non-null  int64
 5   id_tipo_seguro   25150 non-null  int64
 6   prima            20150 non-null  float64
 7   comision         20008 non-null  float64
 8   monto_asegurado  20179 non-null  float64
dtypes: datetime64[ns](1), float64(3), int64(5)
memory usage: 1.7 MB

Number of null values after cleaning:
id_poliza              0
fecha_emision      20628
id_cliente             0
id_corredor            0
id_aseguradora         0
id_tipo_seguro         0
prima               5000
comision            5142
monto_asegurado     4971
dtype: int64

,id_poliza,fecha_emision,id_cliente,id_corredor,id_aseguradora,id_tipo_seguro,prima,comision,monto_asegurado
0,1,NaT,184,42,15,2,829.53,NaN,1.392531e+07
1,2,2026-02-16,2408,35,11,12,NaN,12.22,2.754432e+04
2,3,NaT,540,42,4,9,161153.00,92.05,1.732984e+02
3,4,NaT,2821,40,10,5,186662.00,45699.00,2.444613e+07
4,5,NaT,945,23,9,11,NaN,324.08,1.234078e+07

In [6]:
# Assuming 'prima' and 'monto_asegurado' are key fields to determine a 'valid' policy
polizas_validas = polizas_df[
    polizas_df['prima'].notna() &
    polizas_df['monto_asegurado'].notna()
].copy()

polizas_rechazadas = polizas_df[
    polizas_df['prima'].isna() |
    polizas_df['monto_asegurado'].isna()
].copy()
print('Shape of polizas_validas:', polizas_validas.shape)
print('Shape of polizas_rechazadas:', polizas_rechazadas.shape)

print('\nFirst 5 rows of polizas_validas:')
display(polizas_validas.head())

print('\nFirst 5 rows of polizas_rechazadas:')
display(polizas_rechazadas.head())

Shape of polizas_validas: (16210, 9)
Shape of polizas_rechazadas: (8940, 9)

First 5 rows of polizas_validas:

,id_poliza,fecha_emision,id_cliente,id_corredor,id_aseguradora,id_tipo_seguro,prima,comision,monto_asegurado
0,1,NaT,184,42,15,2,829.53,NaN,1.392531e+07
2,3,NaT,540,42,4,9,161153.00,92.05,1.732984e+02
3,4,NaT,2821,40,10,5,186662.00,45699.00,2.444613e+07
5,6,NaT,1295,17,1,1,94349.00,NaN,7.196843e+06
6,7,NaT,1254,25,11,4,140082.00,18840.00,2.582029e+07

First 5 rows of polizas_rechazadas:

,id_poliza,fecha_emision,id_cliente,id_corredor,id_aseguradora,id_tipo_seguro,prima,comision,monto_asegurado
1,2,2026-02-16,2408,35,11,12,NaN,12.22,27544.32
4,5,NaT,945,23,9,11,NaN,324.08,12340775.00
7,8,NaT,887,77,3,8,167056.0,25875.00,NaN
8,9,NaT,1670,66,8,12,NaN,131.85,12580484.00
10,11,NaT,2590,25,8,4,NaN,NaN,NaN

In [7]:
def motivo_rechazo_poliza(row):
    motivos = []

    if pd.isna(row['fecha_emision']):
        motivos.append('fecha_emision_vacia')

    if pd.isna(row['prima']):
        motivos.append('prima_vacia')

    if pd.isna(row['comision']):
        motivos.append('comision_vacia')

    if pd.isna(row['monto_asegurado']):
        motivos.append('monto_asegurado_vacio')

    return ', '.join(motivos)

polizas_rechazadas_with_motivo = polizas_rechazadas.copy()
polizas_rechazadas_with_motivo['motivo_rechazo'] = polizas_rechazadas_with_motivo.apply(motivo_rechazo_poliza, axis=1)
print('First 5 rows of polizas_rechazadas with motivo_rechazo:')
display(polizas_rechazadas_with_motivo.head())

First 5 rows of polizas_rechazadas with motivo_rechazo:

,id_poliza,fecha_emision,id_cliente,id_corredor,id_aseguradora,id_tipo_seguro,prima,comision,monto_asegurado,motivo_rechazo
1,2,2026-02-16,2408,35,11,12,NaN,12.22,27544.32,prima_vacia
4,5,NaT,945,23,9,11,NaN,324.08,12340775.00,"fecha_emision_vacia, prima_vacia"
7,8,NaT,887,77,3,8,167056.0,25875.00,NaN,"fecha_emision_vacia, monto_asegurado_vacio"
8,9,NaT,1670,66,8,12,NaN,131.85,12580484.00,"fecha_emision_vacia, prima_vacia"
10,11,NaT,2590,25,8,4,NaN,NaN,NaN,"fecha_emision_vacia, prima_vacia, comision_vac..."

In [9]:
polizas_validas.to_csv("polizas_curated.csv", index=False)
polizas_rechazadas_with_motivo.to_csv("polizas_rejects.csv", index=False)

In [10]:
!pip install sqlalchemy psycopg2-binary

from sqlalchemy import create_engine
import pandas as pd

database_url = "postgresql://etl_seguros_67zv_user:TV9HLZks2Q2TRRYt42vPETVOyKIcAYx2@dpg-d6qu70shg0os73b4gfj0-a.oregon-postgres.render.com/etl_seguros_67zv"
engine = create_engine(database_url)

test = pd.read_sql("SELECT 1", engine)

print(test)

Requirement already satisfied: sqlalchemy in /usr/local/lib/python3.12/dist-packages (2.0.48)
Collecting psycopg2-binary
  Downloading psycopg2_binary-2.9.11-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (4.9 kB)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy) (3.3.2)
Requirement already satisfied: typing-extensions>=4.6.0 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy) (4.15.0)
Downloading psycopg2_binary-2.9.11-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (4.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.2/4.2 MB 38.7 MB/s eta 0:00:00
Installing collected packages: psycopg2-binary
Successfully installed psycopg2-binary-2.9.11
   ?column?
0         1

In [11]:
polizas_validas.to_sql(
    'polizas_curated',
    engine,
    if_exists='append',
    index=False
)
polizas_rechazadas_with_motivo.to_sql(
    'polizas_rejects',
    engine,
    if_exists='append',
    index=False
)

940

In [12]:
test_polizas_curated = pd.read_sql(
    "SELECT * FROM polizas_curated LIMIT 10",
    engine
)
display(test_polizas_curated.head())

,id_poliza,fecha_emision,id_cliente,id_corredor,id_aseguradora,id_tipo_seguro,prima,comision,monto_asegurado
0,1,NaT,184,42,15,2,829.53,NaN,1.392531e+07
1,3,NaT,540,42,4,9,161153.00,92.05,1.732984e+02
2,4,NaT,2821,40,10,5,186662.00,45699.00,2.444613e+07
3,6,NaT,1295,17,1,1,94349.00,NaN,7.196843e+06
4,7,NaT,1254,25,11,4,140082.00,18840.00,2.582029e+07